#!/bin/bash
# EC2 Userdata Script
# Generated by Terraform templatefile()

# Variables from template
INSTANCE_NAME="${instance_name}"
REGION="${region}"
ENVIRONMENT="${environment}"

# Update system
yum update -y

# Install packages based on environment
%{ if environment == "prod" ~}
yum install -y httpd mysql
systemctl enable httpd
systemctl start httpd
%{ else ~}
yum install -y httpd
%{ endif ~}

# Create info page
cat > /var/www/html/index.html <<EOF
<html>
<head><title>$INSTANCE_NAME</title></head>
<body>
<h1>Instance: $INSTANCE_NAME</h1>
<p>Region: $REGION</p>
<p>Environment: $ENVIRONMENT</p>
<p>Hostname: $(hostname)</p>
</body>
</html>
EOF

# Log
echo "Instance $INSTANCE_NAME configured in $REGION ($ENVIRONMENT)" >> /var/log/terraform-init.log